DROP TABLE IF EXISTS TASK;

CREATE TABLE TASK (
      `ID`  BIGINT  NOT NULL AUTO_INCREMENT,
      `STATUS`  VARCHAR(64) NOT NULL, -- task 상태 관리
      `TITLE`   VARCHAR(128) NOT NULL,
      `DESCRIPTION` VARCHAR(512) NOT NULL,
      `DUE_DATE` DATE,
      `CREATED_AT`  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
      `UPDATED_AT`  TIMESTAMP(6) AS CURRENT_TIMESTAMP,
      PRIMARY KEY (id)
);